apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Gradle S2I Builder
    openshift.io/image.dockerRepositoryCheck: 2018-05-15T15:04:52Z
  creationTimestamp: 2018-05-15T15:04:52Z
  generation: 3
  name: openjdk-gradle-s2i
  namespace: openshift
  resourceVersion: "7731"
  selfLink: /oapi/v1/namespaces/openshift/imagestreams/openjdk-gradle-s2i
  uid: 51ddf99e-5851-11e8-adb7-0800279d1ac1
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Java applications using Gradle and OpenJDK 8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Gradle S2I Builder
      supports: java:8
      tags: builder,openjdk,xpaas,java,gradle
    from:
      kind: DockerImage
      name: openjdk-gradle-s2i
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: 172.30.1.1:5000/openshift/openjdk-gradle-s2i
  tags:
  - items:
    - created: 2018-05-15T15:05:29Z
      dockerImageReference: 172.30.1.1:5000/openshift/openjdk-gradle-s2i@sha256:72535f8979370ac4745152868f7d613385b38fafe2d12f3f9dc73885d930bb5c
      generation: 1
      image: sha256:72535f8979370ac4745152868f7d613385b38fafe2d12f3f9dc73885d930bb5c
    tag: latest
